insert into T_ADRESSELIEURDV (ADRESSELIEURDV_IDADRESSELIEURDV, ADRESSELIEURDV_NUMERO, ADRESSELIEURDV_PAYS, ADRESSELIEURDV_RUE, ADRESSELIEURDV_VILLE, ADRESSELIEURDV_ZIPCODE) values (1,'6','FRANCE','Rue de la pointe','Nanteuil le Haudouin','60440');
insert into T_LIEURDV (LIEURDV_LIEURDV,LIEURDV_IDADRESSELIEURDV_fk ) values ('La Bonbonniere',1);
insert into T_ADRESSELIEURDV (ADRESSELIEURDV_IDADRESSELIEURDV, ADRESSELIEURDV_NUMERO, ADRESSELIEURDV_PAYS, ADRESSELIEURDV_RUE, ADRESSELIEURDV_VILLE, ADRESSELIEURDV_ZIPCODE) values (2,'23','FRANCE','Avenue du chemin de fer','Villepinte','93420');
insert into T_LIEURDV (LIEURDV_LIEURDV, LIEURDV_IDADRESSELIEURDV_fk) values ('Le Salon', 2);
insert into T_ADRESSELIEURDV (ADRESSELIEURDV_IDADRESSELIEURDV, ADRESSELIEURDV_NUMERO, ADRESSELIEURDV_PAYS, ADRESSELIEURDV_RUE, ADRESSELIEURDV_VILLE, ADRESSELIEURDV_ZIPCODE) values (3,null,null,null,null,null);
insert into T_LIEURDV (LIEURDV_LIEURDV, LIEURDV_IDADRESSELIEURDV_fk) values ('Domicile Clientelle',3);
